# Generated by Django 5.1.5 on 2025-02-01 11:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_remove_faq_language_faq_answer_bn_faq_answer_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer (English)'),
        ),
    ]
